export const MOVIE_ACTION_TYPES = {
  SET_SELECT_MOVIE: "SET_SELECT_MOVIE",
  FETCH_MOVIE_START: "FETCH_MOVIE_START",
  FETCH_MOVIE_SUCCESS: "FETCH_MOVIE_SUCCESS",
  FETCH_MOVIE_FAILED: "FETCH_MOVIE_FAILED",
  // SET_MOVIE: "SET_MOVIE",
  SET_QUERY: "SET_QUERY",
  SET_PİCKMOVİE: "SET_PİCKMOVİE",
  SET_IMDBDATA: "SET_IMDBDATA",
  SET_CLOSERCART: "SET_CLOSERCART",
};
